### ISSUE TITLE
Broken with Thunderbird 128

### ISSUE THREAD

**Issue by Damskibobs** [gazhay/accountcolors#8]
Seems to be broken with Thunderbird 128.
It’s completely stopped working for me.

**Comment by alchemiker** [comment]
Can confirm. Was two weeks on vacation, and now I suffer from the loss of function of this beloved addon.
Apparently they did quite some changes in 128: https://www.thunderbird.net/en-US/thunderbird/128.0/whatsnew/ but an account colour function seems sadly not to be amongst the improvements.
Would be glad to see this addon come back to function!

**Comment by jsmonzani** [comment]
I confirm that it unfortunately doesn't work with "Nebula" version.

**Comment by Betterbird** [comment]
Why don't you just switch to Betterbird which has this function natively, and had it since 115.

**Comment by Damskibobs** [comment]
> Why don't you just switch to Betterbird which has this function natively, and had it since 115.

Thanks for replying @Betterbird 

I excitedly just installed Betterbird to test it.

Unfortunately, it doesn't seem to work!

It does color the accounts, in the left folders panel, but that's not what most people liked about the Account Colors addon.

We want the messages in the inbox to have the colors of the account that they are in. Can Betterbird do this or not? If so, where is the setting?

Unless I'm missing something, Betterbird doesn't change the colors of the list of messages at all. I use the 'Cards View', and all cards are still white.

I also tried the 'Table View'. No change their either.

If Betterbird ever does implement Account Colors, I'll switch to is straight away! Until then, I'm switching back to Thunderbird.

**Comment by Betterbird** [comment]
It only works on virtual folders spanning multiple acounts, like unified folders. Why would you want to colour a single inbox all in the same colour?

But you are correct, the functionality implemented in BB is a subset of what the add-on used to do.

In cards view, it adds a coloured border, and there is a pref for "full row colour", check the release notes or the Expert Tips" page.

UPDATE: Due to TB's poor implementation of its accout colours, you need to set the colour again in the Account Settings since BB uses a different storage location and doesn't "import" the TB colour.

**Comment by Damskibobs** [comment]
> In cards view, it adds a coloured border, and there is a pref for "full row colour", check the release notes or the Expert Tips" page.

BOOM!

The "mail.threadpane.full_row_color" was the answer!

If possible, I'd make that default to 'True', as I'm sure that's what most people will want.

Thanks so much @Betterbird ! I've got Account Colors again !!!

**Comment by Betterbird** [comment]
> If possible, I'd make that default to 'True', as I'm sure that's what most people will want.

We find too much colour overwhelming. Also, it will clash with tag colours. We've been in the TB/BB business long enough to know that user wishes are unpredictable and contradictory, so second-guessing the right option is doomed to fail. Some examples are the TB folks forcing the "Correspondents" column onto everyone, next threading which is totally inappropriate in some context was forced onto users, and we could write a few paragraphs more (paragraph mode, global sort order, etc.).

The target audience of BB are discerning users who are also prepared to study the supplied documentation. You've proven that the pref could be found!

Anyway, it's all off-topic here and mostly advertising for BB, so please excuse the disruption.

---

Coming back add-on issue: The card view in 128 differs from the one in 115, basically another container was introduced, so you now need to fill the new inner container instead of the pre-existing outer container. We had to adjust BB's card colours to that:
https://github.com/Betterbird/thunderbird-patches/commit/143a4b3231e70ebb93d4c30b455bcd00e7250074#diff-2973d75f7811ede1a4ecdd4756ab6ebe73a53c557203798d82b8add186c21cf3L162

It's not a dramatic change, the add-on could be updated for TB users.

**Comment by gazhay** [comment]
Betterbird is indeed the solution.

**Comment by Betterbird** [comment]
We received an e-mail referring to a (deleted) comment saying:
Unless I am mistaken, better bird only background colors the "*" part of the row, the rest of the background is white, so functionality is not quite equivalent?
Please don't delete comments. If you made a mistake or changed your mind, edit them, strike out some stuff, etc.
What's the "*" part??

**Comment by gazhay** [comment]
For completeness, you shouldn't go posting someone's deleted comments.
There are many reasons for deletion and you should respect the decision to delete.

**Comment by Betterbird** [comment]
There is no point deleting a comment that was already shipped out via e-mail. It only confuses people clicking on the link in the e-mail, since it takes them to the start of the ticket. If you want to delete a comment, edit it. We all make mistakes, so there is no shame in recognising a mistake and editing a comment. For a long time, Bugzilla didn't let you edit anything, now users with certain privileges can edit. Only the Bugzilla admins can delete, and they do that very sparingly, only if personal details are accidentally posted, etc.

So closing the ticket means that all your add-on users will now switch to BB?
